platform :ios, '7.0'
inhibit_all_warnings!

pod 'FBSDKCoreKit', '~> 4.4'
pod 'FBSDKLoginKit', '~> 4.4'
pod 'FBSDKShareKit', '~> 4.4'
pod 'VK-ios-sdk', '~> 1.1'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'Reachability', '~> 3.2'
pod 'AFMSlidingCell', '~> 1.0'
pod 'LSSwipeToDeleteCollectionViewLayout', '~> 0.1'